"""add unique field title to model Tasks

Revision ID: c5e34d278c85
Revises: ce1b37907d7b
Create Date: 2025-09-07 18:45:43.599525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5e34d278c85"
down_revision: Union[str, Sequence[str], None] = "ce1b37907d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tasks", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="unique")
    # ### end Alembic commands ###
