"""add comments tasks project models

Revision ID: fc5897d26ed0
Revises: 4686f164f15b
Create Date: 2025-09-04 18:58:09.227491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc5897d26ed0"
down_revision: Union[str, Sequence[str], None] = "4686f164f15b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "avatar_url", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column("users", "avatar_url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
