"""add to model Comments CASCADE delete

Revision ID: 9f7922ee24b5
Revises: e47dd4edf058
Create Date: 2025-09-09 14:47:11.449081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f7922ee24b5"
down_revision: Union[str, Sequence[str], None] = "e47dd4edf058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comments_author_id_fkey"), "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_author_id_fkey"), "comments", "users", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
