"""add project model field name unique

Revision ID: ce1b37907d7b
Revises: 175905bb1fb8
Create Date: 2025-09-05 18:55:02.520813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce1b37907d7b"
down_revision: Union[str, Sequence[str], None] = "175905bb1fb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("projects_owner_id_fkey"), "projects", type_="foreignkey")
    op.create_foreign_key(
        None, "projects", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("projects_owner_id_fkey"), "projects", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
