"""add delete cascade in to model Comments to field task_id

Revision ID: e47dd4edf058
Revises: 5b28be28911b
Create Date: 2025-09-07 21:52:25.310197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e47dd4edf058"
down_revision: Union[str, Sequence[str], None] = "5b28be28911b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comments_task_id_fkey"), "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "tasks", ["task_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_task_id_fkey"), "comments", "tasks", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
